apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  strategy: {}
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres
        name: postgresql
        envFrom:
        - secretRef:
            name: db-env
        resources: {}
status: {}
