apiVersion: v1
kind: ConfigMap
metadata:
  name: queue-service-config
  namespace: mini-msa-app
data:
  PORT: "3001"
  SERVICE_NAME: "queue-service"
  CORE_SERVICE_URL: "http://core-service.mini-msa-app.svc.cluster.local:3002"
  NODE_ENV: "production"
  POSTGRES_HOST: "postgres-service.mini-msa-data.svc.cluster.local"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis-service.mini-msa-data.svc.cluster.local"
  REDIS_PORT: "6379"
