apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: mini-msa-app
  labels:
    app: queue-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: queue-service
