{{- range $key, $ns := .Values.namespaces }}
{{- if $ns.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "mini-msa.namespaceName" (dict "root" $ "key" $key) }}
  labels:
    {{- if $ns.labels }}
    {{- toYaml $ns.labels | nindent 4 }}
    {{- end }}
    kubernetes.io/metadata.name: {{ include "mini-msa.namespaceName" (dict "root" $ "key" $key) }}
  {{- if $ns.annotations }}
  annotations:
    {{- toYaml $ns.annotations | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
