{{- range $id, $secret := .Values.secrets }}
{{- if and $secret.create $secret.name }}
{{- range $idx, $nsKey := $secret.targetNamespaces }}
{{- if not (hasKey $.Values.namespaces $nsKey) }}
{{- fail (printf "namespaces.%s is not defined but is referenced by secret %s" $nsKey $secret.name) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ include "mini-msa.namespaceName" (dict "root" $ "key" $nsKey) }}
  labels:
    {{- include "mini-msa.labels" $ | nindent 4 }}
    app.kubernetes.io/component: secrets
    {{- with $.Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if $secret.labels }}
    {{- toYaml $secret.labels | nindent 4 }}
  {{- end }}
  {{- if $secret.annotations }}
  annotations:
    {{- toYaml $secret.annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $k, $v := $secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
