{{- $root := . -}}
{{- $appNs := include "mini-msa.namespaceName" (dict "root" $root "key" "app") -}}
{{- if and .Values.coreService.enabled .Values.coreService.serviceAccount.create }}
{{- $coreName := include "mini-msa.componentName" (dict "root" $root "suffix" (default "core-service" .Values.coreService.nameSuffix) "override" .Values.coreService.fullnameOverride) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" $coreName) .Values.coreService.serviceAccount.name }}
  namespace: {{ $appNs }}
  labels:
    {{- include "mini-msa.componentLabels" (dict "root" $root "component" "core-serviceaccount") | nindent 4 }}
  {{- with .Values.coreService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.queueService.enabled .Values.queueService.serviceAccount.create }}
{{- $queueName := include "mini-msa.componentName" (dict "root" $root "suffix" (default "queue-service" .Values.queueService.nameSuffix) "override" .Values.queueService.fullnameOverride) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" $queueName) .Values.queueService.serviceAccount.name }}
  namespace: {{ $appNs }}
  labels:
    {{- include "mini-msa.componentLabels" (dict "root" $root "component" "queue-serviceaccount") | nindent 4 }}
  {{- with .Values.queueService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
