# Default values for ticketing-chart.

image:
  repository: 911723818289.dkr.ecr.ap-northeast-2.amazonaws.com
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://ddcn41.com,https://admin.ddcn41.com,https://accounts.ddcn41.com,https://local.ddcn41.com,https://local.admin.ddcn41.com,https://local.accounts.ddcn41.com,http://localhost:3000,http://localhost:3001,http://localhost:3002"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization, X-Requested-With"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix

resources:
  api:
    requests:
      memory: "600Mi"
      cpu: "300m"
    limits:
      memory: "1Gi"
      cpu: "600m"
  admin:
    requests:
      memory: "600Mi"
      cpu: "200m"
    limits:
      memory: "900Mi"
      cpu: "400m"
  queue:
    requests:
      memory: "400Mi"
      cpu: "100m"
    limits:
      memory: "600Mi"
      cpu: "300m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application Specific Configuration
global:
  env:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://ticketing-db.ctc8oem006js.ap-northeast-2.rds.amazonaws.com:5432/ticketing"
    SPRING_DATASOURCE_USERNAME: "postgres"
    SPRING_DATASOURCE_PASSWORD: "ticketing123!"
    SPRING_REDIS_HOST: "ticketing-redis.3bg8kt.ng.0001.apn2.cache.amazonaws.com" # Primary 엔드포인트
    SPRING_REDIS_PORT: "6379"
    SPRING_PROFILES_ACTIVE: "prod"
    JWT_SECRET: "THIS_IS_A_PRODUCTION_JWT_SECRET_KEY_WITH_64_CHARS_1234567890"
    AWS_REGION: "ap-northeast-2"
    COGNITO_USER_POOL_ID: "ap-northeast-2_U5OVPrFCS"
    COGNITO_CLIENT_ID: "3v51kgfg28ku4r5onf9lfijsfj"
    COGNITO_ENABLED: "true"
    COGNITO_REGION: "ap-northeast-2"
    SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

apps:
  api:
    name: ticketing-api
    replicaCount: 1
    port: 8082
    image:
      repository: 911723818289.dkr.ecr.ap-northeast-2.amazonaws.com/guk/ticketing-api
  admin:
    name: ticketing-admin
    replicaCount: 1
    port: 8081
    image:
      repository: 911723818289.dkr.ecr.ap-northeast-2.amazonaws.com/guk/ticketing-admin
  queue:
    name: ticketing-queue
    replicaCount: 1
    port: 8083
    image:
      repository: 911723818289.dkr.ecr.ap-northeast-2.amazonaws.com/guk/ticketing-queue
