apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ticketing-system-main
  name: ticketing-system-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-system-main
  strategy: {}
  template:
    metadata:
      labels:
        app: ticketing-system-main
    spec:
      containers:
      - image: 968190279976.dkr.ecr.ap-northeast-2.amazonaws.com/ddcn41/msa/main 
        name: main
        envFrom:
        - configMapRef:
            name: main-service-config
        - secretRef:
            name: backend-need-endpoint
        - secretRef:
            name: backend-need-key
        resources:
          limits:
            memory: 700Mi
      imagePullSecrets:
      - name: regcred
status: {}
