apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.admin.name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.apps.admin.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.apps.admin.port }}
      targetPort: {{ .Values.apps.admin.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.apps.admin.name }}
