# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.

# 접근 가능한 Node의 IP
[all]
k8s-master ansible_host=172.25.46.10 ip=172.25.46.10
k8s-worker1 ansible_host=172.25.46.20 ip=172.25.46.20
k8s-worker2 ansible_host=172.25.46.21 ip=172.25.46.21

[kube_control_plane]
k8s-master

[etcd]
k8s-master

[kube_node]
k8s-worker1
k8s-worker2

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr

[all:vars]
ansible_user=pjy1221
ansible_become=yes
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
